### ISSUE TITLE
Crash at start with run from terminal

### ISSUE THREAD

**Issue by yodatak** [flathub/com.github.marhkb.Pods#10]
flatpak info com.github.marhkb.Pods 

Pods - Keep track of your podman containers

          ID: com.github.marhkb.Pods
         Ref: app/com.github.marhkb.Pods/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.2
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 11,7 Mo
     Runtime: org.gnome.Platform/x86_64/43
         Sdk: org.gnome.Sdk/x86_64/43

      Commit: 7e5add11c5abc246ec0e951ae10361f2753c288ec7f0646f9ba615d5f8bfae29
      Parent: abea5bc73f9b5e4a0d4718760b675230a40bceebeff3150793ff350a86be2eba
     Subject: Bump to v1.0.2 (c93cd16a)
        Date: 2023-01-09 07:34:15 +0000

flatpak run com.github.marhkb.Pods    
thread 'main' panicked at 'Failed to init GTK/libadwaita: BoolError { message: "Failed to initialize GTK", filename: "/run/build/pods/vendor/gtk4/src/rt.rs", function: "gtk4::rt", line: 153 }', src/main.rs:35:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by marhkb** [comment]
Hi! 
What Distro are you using? Do other gtk4/libadwaita apps work? Have you tried issuing the `repair` command?
```shell
$ flatpak repair
```

**Comment by yodatak** [comment]
After a restart it works weird i think
